### ISSUE TITLE
module extension error

### ISSUE THREAD

**Issue by jmikerq** [artik-iot/artik-sdk#12]
Seems like whenever I try to require that lib/artik-sdk binary file, it comes back with error:

module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: libartik-sdk-base.so.1: cannot open shared object file: No such file or directory
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/lib/node_modules/node-red/node_modules/node-red-contrib-artik/node_modules/artik-sdk/src/gpio.js:3:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

not sure if there is some sort of setup that needs to be done?

**Comment by glemercier** [comment]
This node.js module depends on a native Artik SDK which is not publicly available yet. Stay tuned for new updates, we will provide installation information whenever it is available.

**Comment by jmikerq** [comment]
So would you possibly have a timeline for when it is available? Thanks in advance
