### ISSUE TITLE
Error trying to use the code

### ISSUE THREAD

**Issue by crombie0** [artik-iot/artik-sdk#13]
I've tried running the code, but I've received this error instead. 

`[test@localhost test]$ sudo node wifi-test.js 
[sudo] password for test: 

module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: libartik-sdk-base.so.1: cannot open shared object file: No such file or directory
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/test/artik-sdk/test/wifi-test.js:1:77)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)`

It seems that the file cannot be found. Anyone has any insight into this issue?

**Comment by crombie0** [comment]
Never mind I've just seen the previously closed issues. Keep me updated when the module is publicly out!
